name: passputter
description: Easily authenticate using OAuth 2.0 client/password grants.
version: 2.0.0
repository: https://github.com/netsells/passputter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  dio: ^4.0.0
  meta: ^1.7.0

dev_dependencies:
  import_sorter: ^4.5.0
  mock_web_server: ^5.0.0-nullsafety.1
  mocktail: ^0.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  test: ^1.17.3
  time: ^2.0.0
  very_good_analysis: ^2.0.3

import_sorter:
  emojis: true
